### ISSUE TITLE
A couple comments and a question

### ISSUE THREAD

**Issue by curtisshipley** [neverlostmine/ts-node-claudia#1]
Thanks for doing this. It is really helpful!

1) You may want to add the .vscode to .gitignore. When I pulled it down, my vscode fonts went wonky and it took me a bit to figure out what happened.

2) I'm guessing this was developed on windows? You may want to add a note to the readme that on linus/osx the build command in package.json should use "cp" instead of "copy".

Now my question:

To change the name of my lambda, do I just need to change "name" and "role" in claudia.json?

**Comment by gong-hao** [comment]
lol, I'm sorry about the .vscode. I have removed it.

I added the two build scripts for different OS.

It seems like there is no way to rename a lambda function unless you recreate it.

However, if you have an existing lambda function, you probably can add the info into the claudia.json, and it should work for update (if this is also created by claudia before).

By the way, I have updated a new version that might have the better structure and full testing. Welcome to give me any comments.
